// CHANGE PASSWORD
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

// WOUNDED ANIMAL
export const WOUNDED_ANIMAL_REQUEST = 'WOUNDED_ANIMAL_REQUEST';
export const WOUNDED_ANIMAL_SUCCESS = 'WOUNDED_ANIMAL_SUCCESS';
export const WOUNDED_ANIMAL_FAIL = 'WOUNDED_ANIMAL_FAIL';
